default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: car_development
  host: localhost
  port: 5432
  username: rails
  password: password
  
production:
  <<: *default
  database: car_production
  # username: freelance
  # password: <%= ENV['FREELANCE_DATABASE_PASSWORD'] %>
